{% set python_min = "3.12" %}
{% set name = "sunkit-magex" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/sunkit_magex-{{ version }}.tar.gz
  sha256: 4a86e92d92b4f34832445c7aed0e41c2d66a6f03132c8e233f4178dd3bbe260c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62.1
    - setuptools-scm >=8.0.1
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - astropy-base >=6.1.0
    - numpy >=1.26.0
    - scikit-image >=0.22.0
    - scipy >=1.12.0
    - streamtracer >=2.2.0
    - sunpy >=7.0
    - matplotlib-base >=3.8.0

test:
  imports:
    - sunkit_magex
  commands:
    - pip check
    - pytest --doctest-rst -p no:unraisableexception -p no:threadexception --arraydiff --pyargs sunkit_magex
  requires:
    - pip
    - pytest
    - pytest-doctestplus
    - pytest-arraydiff
    - parfive
    - reproject
    - streamtracer
    - sympy
    - python {{ python_min }}

about:
  home: https://sunpy.org
  summary: Solar Magnetic field Extrapolation
  license: GPL-3.0-only
  license_file: licenses/LICENSE.rst
  doc_url: https://docs.sunpy.org/projects/sunkit-magex/
  dev_url: https://github.com/sunpy/sunkit-magex

extra:
  recipe-maintainers:
    - jgieseler
    - Cadair
    - STBadman
